### ISSUE TITLE
Quick Start: cannot import name 'filestore_v1' from 'google.cloud'

### ISSUE THREAD

**Issue by iojohnso** [GoogleCloudPlatform/vertex-ai-alphafold-inference-pipeline#11]
Running into this error when running the quick start:

![image](https://user-images.githubusercontent.com/2060865/193883236-781e5ffe-13a1-4694-b06a-060441d68a0b.png)

This is likely alleviated by adding ```google-cloud-filestore``` to the initial pip install

![image](https://user-images.githubusercontent.com/2060865/193883626-e62c6739-deb0-496d-bb2c-2fa6bf537b70.png)

**Comment by leiterenato** [comment]
Fix in the latest commit.
Thanks for the heads up, I was using an environment with the Filestore SDK already installed.
