### ISSUE TITLE
Exploration Enhancement: is_universal_pipeline and is_monomer no longer needed?

### ISSUE THREAD

**Issue by iojohnso** [GoogleCloudPlatform/vertex-ai-alphafold-inference-pipeline#13]
With the latest enhancements to the quick start notebooks, are the following variables needed anymore?  Can these be determined by the pipeline metadata?

![image](https://user-images.githubusercontent.com/2060865/194605325-f8d9ce93-09eb-42ee-b222-1e2b1e44ade8.png)

Thanks,
Isaac

**Comment by leiterenato** [comment]
Hi @iojohnso,
No, you don't have to set these variables anymore.
We implemented this utility to check if the fasta is a monomer or multimer.

https://github.com/GoogleCloudPlatform/vertex-ai-alphafold-inference-pipeline/blob/main/src/utils/fasta_utils.py

We also check if there are any sequences and if their length > 0.
