### ISSUE TITLE
[FEAT] Easy to find linkage between CustomJobs and PipelineJob

### ISSUE THREAD

**Issue by iojohnso** [GoogleCloudPlatform/vertex-ai-alphafold-inference-pipeline#19]
Is there an easy way to link CustomJobs back to the Pipeline runs that kicked them off?

Something like a parentPipelineJobName would likely be helfpul.  Would this happen to be the intent of the empty label that is currently on the CustomJobs?

<img width="322" alt="image" src="https://user-images.githubusercontent.com/2060865/199841841-4fb6381f-605e-4303-8d4e-5381c054d8b6.png">

I do notice there are some string references within the -args of the job that infer where it came from...

<img width="522" alt="image" src="https://user-images.githubusercontent.com/2060865/199842168-895a9186-1c2e-43b1-8cc9-71f33b5dc8ff.png">

Or, maybe the only way to clearly link this is from the PipelineJob to the child Custom Job...

<img width="704" alt="image" src="https://user-images.githubusercontent.com/2060865/199842693-5f2dd43d-9aa2-475c-a04a-6626a2475a9e.png">

**Comment by leiterenato** [comment]
To link the PipelineJob => CustomJob, you have to retrieve this information from the PipelineJob (your last example).

You would need to list the pipeline job by its ID, like this:

```
get_request = vertex_ai.GetPipelineJobRequest(
    name=pipeline_id
)
pipeline_job = client_pipeline.get_pipeline_job(get_request)
```

And parse the `pipeline_job` proto message to get the container executions.
We gave some examples on how to use the API in notebook #2.
https://github.com/GoogleCloudPlatform/vertex-ai-alphafold-inference-pipeline/blob/main/2-alphafold-metadata-exploration.ipynb

Please let me know if you have any question on how to get to this point.

**Comment by iojohnso** [comment]
Thanks, @leiterenato.  I was able to pull and extract the information through the API as mentioned.
