### ISSUE TITLE
Add PAE presentation in the notebook of 3_pipelines_experiment_metadata.ipynb

### ISSUE THREAD

**Issue by JasperW01** [GoogleCloudPlatform/vertex-ai-alphafold-inference-pipeline#2]
Would be great if we could add PAE diagram presentation in the notebook of 3_pipelines_experiment_metadata.ipynb. It’s called the Predicted Aligned Error and is sourced from the pkl files. 

The data is hidden in the pkl file output and needed to be programmed to present its graph. This graph is the critical output the biologists need to see how the run has gone but not straightforward for them to access. An example is attached below (the right part of it)

![image](https://user-images.githubusercontent.com/14971090/181876072-e2a5bba8-ff96-48b4-a247-a4325bab2d1e.png)

Also quoted the PAE detailed definition from https://alphafold.ebi.ac.uk/faq as below as reference: 

_The Predicted Aligned Error (PAE) is displayed as an image for each of the structure predictions. If you need the raw data with PAE for all residue pairs, you can download the PAE in a JSON format using the button at the top of the structure page.

This file is in a custom format and it isn't supported by any existing software – you will have to use Python or any other scripting language to process and plot the information that is contained in it.

For a protein of length num_res, the JSON has the following structure of arrays format:
[
    {
        "residue1": [ 1, 1, 1, 1, 1, ...], # Length: num_res^2.
        "residue2": [ 1, 2, 3, 4, 5, ...], # Length: num_res^2.
        "distance": [0.2, 1.2, 3.7, 6.6, 8.7, ...], # Length: num_res^2.
        "max_predicted_aligned_error": 31.75
    }
]

The fields in the JSON are:

residue1: The residue on which the structure is aligned for the predicted error.
residue2: The residue on which the error is predicted.
distance: The PAE value of the residue pair.
max_predicted_aligned_error: A scalar that denotes the maximum possible value of PAE. The minimum PAE is 0.
Since distance contains values for all residue pairs, it can be used directly by reshaping to a 2D matrix of shape [num_res, num_res]._

**Comment by leiterenato** [comment]
@JasperW01 I created a new branch [HERE](https://github.com/GoogleCloudPlatform/vertex-ai-alphafold-inference-pipeline/tree/af-pae-chart) and added the PAE chart to the notebook number 03.

Could you please check out, test and validate if this is the expected result?

**Comment by JasperW01** [comment]
I have just tested and verified it's all working fine. Thx a lot for adding this feature, @leiterenato , which is popular with researchers.
