### ISSUE TITLE
[FEAT] - Add 'DATA_PIPELINE_MACHINE_TYPE' environ example to quick start notebook

### ISSUE THREAD

**Issue by iojohnso** [GoogleCloudPlatform/vertex-ai-alphafold-inference-pipeline#20]
We were hitting out of memory errors during the 'Prepare Features' step.  We were able to track down in the code where the machine type was defined, but it was a bit hidden.

I would suggest adding this environ as a commented out example with the rest of the environs that can be set.  Example below:

![image](https://user-images.githubusercontent.com/2060865/203637166-41f5edbf-6439-4ed4-9025-9fd586e5fa4d.png)

**Comment by leiterenato** [comment]
This is a good suggestion.
Would you create a pull request so I can merge to main?

**Comment by leiterenato** [comment]
Fixed.
