### ISSUE TITLE
msa_uri is empty in No. 2 notebook 

### ISSUE THREAD

**Issue by JasperW01** [GoogleCloudPlatform/vertex-ai-alphafold-inference-pipeline#22]
In the No. 2 notebook, the msa_uri step now returns empty string which was working previously. It causes the step of showing MSA hit diagram fails in the No. 2 notebook.

**Comment by leiterenato** [comment]
@JasperW01 
I fixed this issue by listing the Storage Bucket and retrieving the MSA files directly.  
Can you please update your codebase and retest it?

**Comment by JasperW01** [comment]
@leiterenato 
It's all working now. Thx a lot.
