### ISSUE TITLE
Container building failed due to dependency since early March 2024

### ISSUE THREAD

**Issue by JasperW01** [GoogleCloudPlatform/vertex-ai-alphafold-inference-pipeline#48]
Since early March 2024, it's found that the AlphaFold container images built via Alphafold.dockerfile & Alphafold1.dockerfile_cuda1111 both failed due to the same error below: 

LibMambaUnsatisfiableError: Encountered problems while solving:
  - package conda-23.1.0-py310h06a4308_0 requires python >=3.10,<3.11.0a0, but none of the providers
 can be installed

Could not solve for environment specs
The following packages are incompatible
├─ conda 23.1.0  is installable with the potential options
│  ├─ conda 23.1.0 would require
│  │  └─ python >=3.10,<3.11.0a0 , which can be installed;
│  ├─ conda 23.1.0 would require
│  │  └─ python >=3.11,<3.12.0a0 , which can be installed;
│  ├─ conda 23.1.0 would require
│  │  └─ python >=3.7,<3.8.0a0 , which can be installed;
│  ├─ conda 23.1.0 would require
│  │  └─ python >=3.8,<3.9.0a0 , which can be installed;
│  └─ conda 23.1.0 would require
│     └─ python >=3.9,<3.10.0a0 , which can be installed;
└─ pin-1 is not installable because it requires
   └─ python 3.12.* , which conflicts with any installable versions previously reported.

Pins seem to be involved in the conflict. Currently pinned specs:
 - python 3.12.* (labeled as 'pin-1')

The command '/bin/bash -o pipefail -c conda install -qy conda==23.1.0     && conda install -y -c
 conda-forge       openmm=7.5.1       pdbfixer       pip       python=3.9       && conda install -y -c nvidia/label/cuda-${CUDA} cuda-libraries-dev cuda-nvcc cuda-nvtx cuda-cupti       && conda clean --all --force-pkgs-dirs --yes' returned a non-zero code:
 1
ERROR
ERROR: build step 0 "[gcr.io/cloud-builders/docker](http://gcr.io/cloud-builders/docker)" failed: step exited with non-zero status:
 1

The route cause is python library dependencies. In order to solve it, two changes are needed in both dockerfile: 

1. Align with the Deepmind AlphaFold github repo's https://github.com/google-deepmind/alphafold/blob/main/docker/Dockerfile to upgrade the version of conda, openmm, python. 
2. Also need to clone from Deepmind AlphaFold github repo's main branch instead of v2.3.2 branch. Otherwise the older version of https://github.com/google-deepmind/alphafold/blob/main/requirements.txt will cause dependency issue which fails the container building.

**Comment by yudyhendry** [comment]
https://github.com/GoogleCloudPlatform/vertex-ai-alphafold-inference-pipeline/pull/49/files/4452f92e7907b2135ad3680fef0e03a843fd534d has fixed this issue
