### ISSUE TITLE
Consider Adding a Wait Mechanism or Similar at end of Notebooks

### ISSUE THREAD

**Issue by iojohnso** [GoogleCloudPlatform/vertex-ai-alphafold-inference-pipeline#8]
If users set the necessary notebook parameters and then 'Run All Cells', they will typically experience an error in the very last ```pipeline_job.state``` step because the job run hasn't been created yet.  If you re-run this step after a few seconds it will usually complete after the job has been created. 

Consider adding a simple 'sleep' or other means to avoid end-user confusion:

```python
# Wait about 5 seconds to allow the job run request to complete
import time
time.sleep(5)

# Check the state of the pipeline
pipeline_job.state
```

Error below...

![image](https://user-images.githubusercontent.com/2060865/193630059-36632490-0ca0-4c8a-b52f-392b1053dbe8.png)

**Comment by leiterenato** [comment]
Hi @iojohnso 
Thanks for summiting this suggestion.
I agree and I will implement it.

We can use the `_wait_for_resource_creation` from the SDK to properly wait for the resource creation:
https://github.com/googleapis/python-aiplatform/blob/6190088304f8bb02bd86ec0bcc6f7e526288cd9e/google/cloud/aiplatform/base.py#L1275

Thank you again.
Cheers

**Comment by leiterenato** [comment]
Problem fixed in our last commit.
Thanks again.
